version: "3"

services:
  gophish:
    build:
      context: ./etc/gophish/
    container_name: gophish-prod
    restart: unless-stopped
    ports:
      - "3333:3333"
      - "8080:8080"
    networks:
      - default
  nginx:
    build:
      context: ./etc/nginx/
    container_name: gophish-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default

networks:
  default:
